/**
 * Productos Santa Rosa
 * Módulo: Compras (Insumos)
 * Versión: 1.0.0
 * Build: 20260925.2225
 * Objetivo: Historial de compras y captura rápida integrada con Mercado.
 */

import {getPurchases,productNames,observationsForProduct,purchasesForProduct,placeById,addPurchase,addObservation,getPlaces,savePhoto,getPhoto,normalize} from '../mercado/mercado-store.js';
const root=document.getElementById('app'); let query='';let selected='';let sectionOpen={summary:false,purchases:false};let photoIds=[];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nav=()=>`<nav class="app-navbar"><div class="app-brand">🍓 Santa Rosa</div><a class="app-navlink" href="/productos-santa-rosa/pages/mercado/">🏪 Mercado</a><a class="app-navlink active" href="/productos-santa-rosa/pages/insumos/">📦 Compras</a><a class="app-navlink" href="/productos-santa-rosa/pages/mapa/">🗺️ Mapa</a></nav>`;
function render(){const ps=productNames().filter(p=>!query||normalize(p).includes(normalize(query)));const purchases=getPurchases();const total=purchases.reduce((s,p)=>s+Number(p.total||0),0);root.innerHTML=nav()+`<div class="app-head"><div><h1>Compras</h1><div class="muted">Historial de compras de insumos</div></div></div><div class="search-row"><input id="q" class="search" value="${esc(query)}" placeholder="🔎 Buscar producto..."><button class="btn secondary filter-btn" id="newBuy">+ Compra</button></div><div class="grid">${ps.map(p=>{const rows=purchasesForProduct(p);const last=rows[0];return `<button class="tile" data-product="${esc(p)}"><span class="tile-icon">📦</span><span class="tile-name">${esc(p)}</span><span class="tile-meta">${rows.length} compras · ${last?'$'+Number(last.precio||0).toFixed(2):'—'}</span></button>`}).join('')}</div><div class="section ${sectionOpen.summary?'':'closed'}"><button class="section-title" data-sec="summary">📊 Resumen <span>${sectionOpen.summary?'▲':'▼'}</span></button><div class="section-body"><div class="stats"><span class="stat">${purchases.length} compras</span><span class="stat">$${total.toFixed(2)} total</span><span class="stat">${new Set(purchases.map(p=>p.producto)).size} productos</span></div></div></div><div class="section ${sectionOpen.purchases?'':'closed'}"><button class="section-title" data-sec="purchases">📋 Historial <span>${sectionOpen.purchases?'▲':'▼'}</span></button><div class="section-body list">${purchases.sort((a,b)=>new Date(b.fecha)-new Date(a.fecha)).slice(0,100).map(p=>`<div class="row-card"><div class="row-main"><div><b>${esc(p.producto)}</b><div class="muted">${esc(p.tienda||'Lugar')} · ${new Date(p.fecha).toLocaleDateString('es-MX')}</div></div><span class="price">$${Number(p.total||0).toFixed(2)}</span></div><div class="hint">${Number(p.cantidad||0)} ${esc(p.presentacion||'u')} · $${Number(p.precio||0).toFixed(2)} c/u</div></div>`).join('')||'<div class="empty">No hay compras registradas.</div>'}</div></div><div class="modal" id="modal"></div>`;bind();}
function openBuy(product=selected){photoIds=[];const m=document.getElementById('modal');m.className='modal open';m.innerHTML=`<div class="modal-box"><h2>🛒 Nueva compra</h2><div class="form-grid"><div class="field full"><label>Producto *</label><input id="bProduct" value="${esc(product)}" list="productList"></div><div class="field full"><label>Lugar *</label><select id="bPlace"><option value="">Selecciona un lugar</option>${getPlaces().map(p=>`<option value="${p.id}">${esc(p.nombre)}</option>`).join('')}</select></div><div class="field"><label>Precio *</label><input id="bPrice" type="number" min="0" step="0.01" inputmode="decimal"></div><div class="field"><label>Cantidad *</label><input id="bQty" type="number" min="0.01" step="0.01" value="1" inputmode="decimal"></div><div class="field"><label>Presentación</label><input id="bPresentation" placeholder="kg, pza, caja..."></div><div class="field"><label>Comprador</label><select id="bBuyer"><option>Fara</option><option>Martha</option><option>Ambos</option><option>Otro</option></select></div><div class="field full"><label>Foto</label><input id="bPhoto" type="file" accept="image/*" capture="environment"><div id="bPreview" class="photo-preview"></div></div></div><datalist id="productList">${productNames().map(p=>`<option value="${esc(p)}">`).join('')}</datalist><div class="modal-actions"><button class="btn secondary" id="cancel">Cancelar</button><button class="btn" id="save">Guardar compra</button></div></div>`;document.getElementById('bPhoto').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const p=getPlaces().find(x=>x.id===document.getElementById('bPlace').value);if(!p){alert('Selecciona primero el lugar para asociar correctamente la foto.');e.target.value='';return;}try{photoIds=[await savePhoto(f,p.nombre)];document.getElementById('bPreview').innerHTML='<span class="hint">✓ Foto comprimida y lista</span>';}catch(err){alert(err.message);}};document.getElementById('cancel').onclick=()=>m.className='modal';document.getElementById('save').onclick=()=>{const product=document.getElementById('bProduct').value.trim();const place=getPlaces().find(x=>x.id===document.getElementById('bPlace').value);const price=Number(document.getElementById('bPrice').value);const qty=Number(document.getElementById('bQty').value);if(!product||!place||!(price>=0)||!(qty>0)){alert('Completa producto, lugar, precio y cantidad.');return;}const pres=document.getElementById('bPresentation').value;addPurchase({producto:product,presentacion:pres,tienda:place.nombre,clienteId:place.id,comprador:document.getElementById('bBuyer').value,cantidad:qty,precio:price,total:qty*price,contacto:place.contacto||place.telefono,direccion:place.direccion,latitud:place.latitud,longitud:place.longitud,photoIds});addObservation({producto:product,presentacion:pres,precio:price,clienteId:place.id,photoIds});m.className='modal';selected=product;render();};}
function bind(){document.getElementById('q')?.addEventListener('input',e=>{query=e.target.value;render()});document.getElementById('newBuy')?.addEventListener('click',()=>openBuy(''));document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{selected=b.dataset.product;openBuy(selected)});document.querySelectorAll('[data-sec]').forEach(b=>b.onclick=()=>{const s=b.dataset.sec;sectionOpen[s]=!sectionOpen[s];render()});}
render();
